---
title: 'Simulated data for WCGNA demonstration'
author: "Samuel O Skinner"
date: "April 11, 2017"
output:
  html_document:
    number_sections: yes
---


```{r global_opts, echo=FALSE, cache=FALSE}
knitr::opts_chunk$set(fig.width=8, fig.height=4, fig.align='center',
                      echo=TRUE, warning=FALSE, message=FALSE,
                      cache=FALSE, autodep=TRUE)
# knitr::opts_knit$set(root.dir = "..")

## numbers >= 10^5 will be denoted in scientific notation,
## and rounded to 2 digits
options(scipen = 1, digits = 5)
```


# Summary


----- 

# R environment set-up

## Loading packages

```{r load_packages, cache=FALSE}
# Clean up the environment
rm(list = ls())
cleanup <- gc(verbose = FALSE)

# Load libraries I'll need here
library(MASS)
library(dplyr)
library(limma)
library(edgeR)
library(readr)
library(readxl)
library(ggplot2)
library(cowplot)
library(reshape2)
library(WGCNA)
library(gplots)
library(corrplot)
library(caret)
library(leaps)

library(glmnet)

# Packages for R markdown stuff
library(knitr)
library(shiny)

# Required for WGCNA to work properly
options(stringsAsFactors = FALSE)
```


# Create simulated data

## Two anticorrelated networks
```{r simulate_data}

# For all simulated networks, start with correlation matrix

C <- matrix(c(1, 1, 1, 1,-1,-1,-1,-1,
              1, 1, 1, 1,-1,-1,-1,-1,
              1, 1, 1, 1,-1,-1,-1,-1,
              1, 1, 1, 1,-1,-1,-1,-1,
             -1,-1,-1,-1, 1, 1, 1, 1,
             -1,-1,-1,-1, 1, 1, 1, 1,
             -1,-1,-1,-1, 1, 1, 1, 1,
             -1,-1,-1,-1, 1, 1, 1, 1), 
            nrow = 8, 
            ncol = 8,
            byrow = TRUE)

A <- (abs(0.5 + 0.5*C))^6
W <- TOMsimilarity(A, verbose=0)


corrplot(C)

corrplot(W)

```


## Two independent networks
```{r simulate_data}

# For all simulated networks, start with correlation matrix

C <- matrix(c(1, 1, 1, 1,0,0,0,0,
              1, 1, 1, 1,0,0,0,0,
              1, 1, 1, 1,0,0,0,0,
              1, 1, 1, 1,0,0,0,0,
             0,0,0,0, 1, 1, 1, 1,
             0,0,0,0, 1, 1, 1, 1,
             0,0,0,0, 1, 1, 1, 1,
             0,0,0,0, 1, 1, 1, 1), 
            nrow = 8, 
            ncol = 8,
            byrow = TRUE)

A <- (abs(0.5 + 0.5*C))^6
W <- TOMsimilarity(A, verbose=0)


corrplot(C)

corrplot(W)

```




## Hodgepodge
```{r simulate_data}

# For all simulated networks, start with correlation matrix

C <- matrix(c( 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
               1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
               0.8, 0.8, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0,
               0.8, 0.8, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0,
              -1.0,-1.0, 0.5, 0.5, 1.0, 0.0, 0.0, 0.0,
              -1.0,-1.0, 0.5, 0.5, 1.0, 1.0, 0.0, 0.0,
               0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0,
               0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0), 
            nrow = 8, 
            ncol = 8,
            byrow = TRUE)

C <- ifelse(abs(t(C))>abs(C), t(C), C)

A <- (abs(0.5 + 0.5*C))^6
W <- TOMsimilarity(A, verbose=0)


corrplot(C)

corrplot(W)

```


